### ISSUE TITLE
Incorrect hash definition syntax for Ruby

### ISSUE THREAD

**Issue by ohookins** [datawire/mdk#107]
```
/Users/oliver/.rvm/gems/ruby-2.1.8@datawire/gems/quark-1.0.406/lib/quark.rb:3:in `require_relative': /Users/oliver/.rvm/gems/ruby-2.1.8@datawire/gems/quark-1.0.406/lib/datawire-quark-core.rb:146: syntax error, unexpected ':', expecting => (SyntaxError)
      result.value = File.read(path, {"encoding": "UTF-8"})
                                                 ^
/Users/oliver/.rvm/gems/ruby-2.1.8@datawire/gems/quark-1.0.406/lib/datawire-quark-core.rb:146: syntax error, unexpected '}', expecting keyword_end
      result.value = File.read(path, {"encoding": "UTF-8"})
```

Seems like it could actually be an error in the Quark compiler, but I had a quick look and couldn't spot anything obvious in master (to me at least).

**Comment by ohookins** [comment]
Actually I think the bug is indeed in https://github.com/datawire/quark:
https://github.com/datawire/quark/blob/5a150065e569a4666bfed8a447e9aaab0fa10240/quarkc/lib/datawire-quark-core.rb#L146

**Comment by itamarst** [comment]
Hi,

Sorry you're getting errors, and thanks for looking a bit more into it.

We only support Ruby 2.3 at the moment, so we don't test with older versions. Could you try with Ruby 2.3 and see if it works?

Thanks,
-Itamar

**Comment by ohookins** [comment]
Indeed, seems to work as expected with Ruby 2.3.
