### ISSUE TITLE
[python] Python 3 support

### ISSUE THREAD

**Issue by failedguidedog** [datawire/mdk#86]
At this time (MDK v2.0) installing in Python 3.x environment fails:

``` bash
$ curl -# -L https://raw.githubusercontent.com/datawire/mdk/master/install.sh | bash -s -- --python
######################################################################## 100,0%
= Installing the Datawire MDK from master
You seem to have Python $PYVER installed. We only support Python 2,
and we need 2.7 or higher. Check out https://www.python.org to get
that sorted out.
```

Python 3 has been around since 2008 and we're using it in all our projects at my company. As much as we like what Datawire offers, unfortunately it means that we can't use it at this time :(
As far as I understand this is a limitation of the quark compiler?

What I'm hoping for is that this issue can show there are many of us that would like to use Datawire in our Python 3 projects and the support would be greatly appreciated :)

:+1:

**Comment by bozzzzo** [comment]
We didn't update the documentation yet, but as of today you can just `pip3 install datawire_mdk`

**Comment by failedguidedog** [comment]
@bozzzzo Thank you! Will try and get back to you.

**Comment by itamarst** [comment]
Docs will go out on next release, so closing this as it's now fixed.
